// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gutgcdfqasdkmhgxobch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1dGdjZGZxYXNka21oZ3hvYmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjcyNTksImV4cCI6MjA2Njk0MzI1OX0.f4WkIvG2gl34dQcuHM69wh7eTI-ad4CIVS6h29faVUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});