// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsyjnyxazrgcapeikgge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzeWpueXhhenJnY2FwZWlrZ2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzYzNzIsImV4cCI6MjA2NzAxMjM3Mn0.BFSJg3Femv0B3gQZXX6L_mgxWdjDn1JcRYta8Km6Xl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});